build: off

environment:
      SBV_TEST_ENVIRONMENT: win
      SBV_HEAVYTEST_PERCENTAGE:  0
      TASTY_HIDE_SUCCESSES: True

before_build:
- git clone -q https://github.com/Z3Prover/bin.git Z3Prover
- 7z e C:\projects\sbv\Z3Prover\nightly\z3*x64*win*zip -oc:\projects\sbv\z3_downloaded -r
- choco install -y cabal
- choco install -y ghc --version 8.6.2
- refreshenv
- set PATH=C:\projects\sbv\z3_downloaded;%PATH%
- ghc --version
- z3 --version

skip_tags: true

build_script:
- cabal update
- cabal install alex
- cabal install happy
- cabal install --only-dependencies --enable-tests --enable-benchmarks
- cabal build
- cabal test SBVTest
- cabal test SBVDocTest
- cabal test SBVHLint
- cabal check
- cabal sdist
